// This interface defines the structure of a ToDo object.
// In other words, it reflects exactly what a client entry
// looks like in the PostgreSQL database. (One of the entries that
// gets returned from "SELECT * FROM todos").

export interface ToDo {
  // id is a number automatically generated by PostgreSQL (serial primary key)
  id: number;

  // Title of the todo
  title: string;

  // description of the todo
  text: string;
}

// This is used for creating a new ToDo item
export interface ToDoCreateInput {
  // Title of the todo
  title: string;

  // description of the todo
  text: string;
}
